name: React Native CI

on:
  push:
    branches:
      - origin/Javier
      - kev
      - develop
      - main
  pull_request:
    branches:
      - origin/Javier
      - kev
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Tests
        run: |
          npm test -- --coverage

      #- name: Build APK (for React Native projects)
       # run: |
        #  npm run android
