name: React Native CI/CD

on:
  push:
    branches:
      - kev
      - dev
      - main
  pull_request:
    branches:
      - kev
      - dev
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 

      - name: Install dependencies
        run: |
          npm install -g eas-cli # Instala EAS CLI
          npm install --legacy-peer-deps # Evita conflictos de dependencias

      - name: Run Tests
        run: |
          npm test -- --coverage --watchAll=false

      - name: Build with EAS
        run: |
          eas build --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
=======
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g expo-cli@^6.0.0  # Versión compatible con Expo 53
          npm install

      - name: Run Tests
        run: |
          npm test -- --coverage
>>>>>>> aa8a5072493d7e3c0f337468684da205bf01505d
